name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: trietpsu29
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          plugin_lines: yes

      - name: Commit metrics.svg
        run: |
          git config --global user.email "github-actions-bot@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add github-metrics.svg
          git diff
          git commit -m "Update github-metrics.svg" || echo "No changes to commit"
          git push
