name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # metrics.svg: GitHub profile only
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          user: trietpsu29
          template: terminal
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: Asia/Ho_Chi_Minh

          # GitHub activity
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

          # GitHub languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # GitHub lines history
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

      # code.svg: LeetCode + WakaTime combined
      - uses: lowlighter/metrics@latest
        with:
          filename: code.svg
          token: NOT_NEEDED

          user: trietpsu29
          template: classic
          base: ""
          config_timezone: Asia/Ho_Chi_Minh

          # LeetCode stats
          plugin_leetcode: yes
          plugin_leetcode_user: trietpsu29
          plugin_leetcode_sections: solved
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_ignore_skills: hash table, string, divide and conquer, fundamental
          plugin_leetcode_limit_recent: 2

          # WakaTime stats
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: trietpsu29
